language: node_js

cache:
  npm: true
  directories:
    - ./GoodContracts
  
env:
  global:
    - GUNDB_PASS=test
    - MNEMONIC="choice congress hobby buddy dutch busy army eager empty solution start grunt"
    - NETWORK=truffle
    - LOG_LEVEL=trace

before_install:
  - npm install -g ganache-cli truffle webpack
  
before_script:
  - ganache-cli -m "$MNEMONIC" --port 9545 --networkId 4447 -g 10000000000 &
  - cp truffle.test.js node_modules/@gooddollar/goodcontracts/truffle.js
  - cd node_modules/@gooddollar/goodcontracts  
  - truffle migrate --reset --network development
  - cd ../../..

script:
  - npm run coverage
  - npm run build
