language: node_js

cache:
  npm: true
  
env:
  global:
    - GUNDB_PASS=test
    - MNEMONIC="choice congress hobby buddy dutch busy army eager empty solution start grunt"
    - NETWORK=truffle
    - LOG_LEVEL=trace

before_install:
  - npm install -g ganache-cli truffle webpack
  
before_script:
  - export CONTRACTSTAG=`node -pe "require('./node_modules/@gooddollar/goodcontracts/package.json').version"`
  - git clone https://github.com/GoodDollar/GoodContracts --branch=v$CONTRACTSTAG
  - ganache-cli -m "$MNEMONIC" --port 9545 --networkId 4447 -g 10000000000 &
  - cd GoodContracts || true
  - npm i
  - truffle migrate --reset --network develop
  - git reset --hard
  - npm link
  - cd ..

script:
  - npm link @gooddollar/goodcontracts
  - npm run coverage
  - npm run build
