language: node_js

cache:
  npm: true
  directories:
    - ./GoodContracts
  
env:
  global:
    - GUNDB_PASS=test
    - MNEMONIC="choice congress hobby buddy dutch busy army eager empty solution start grunt"
    - NETWORK=truffle
    - LOG_LEVEL=trace

before_install:
  - npm install -g ganache-cli truffle webpack
  
before_script:
  - if cd GoodContracts; then git reset --hard; git pull; else https://github.com/GoodDollar/GoodContracts; fi
  - cp -R node_modules/@gooddollar/goodcontracts/contracts GoodContracts/contracts
  - ganache-cli -m "$MNEMONIC" --port 9545 --networkId 4447 -g 10000000000 &
  - cd GoodContracts || true
  - truffle migrate --reset --network develop
  - git reset --hard
  - cd ..

script:
  - npm run coverage
  - npm run build
